apiVersion: apps/v1
kind: Deployment
metadata:
  name: stylehub-deployment
  labels:
    app: stylehub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stylehub
  template:
    metadata:
      labels:
        app: stylehub
    spec:
      containers:
      - name: stylehub-container
        image: poojabhavani08/stylehub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
