apiVersion: v1
kind: Service
metadata:
  name: stylehub-service
  labels:
    app: stylehub
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: stylehub
---
apiVersion: v1
kind: Service
metadata:
  name: stylehub-nodeport
  labels:
    app: stylehub
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: stylehub
