version: '3'

services:
  web:
    build: .
    ports:
<<<<<<< HEAD
      - "8080:80"
=======
      - "3000:80"
>>>>>>> 05da805 (Resolved merge conflict and added Jenkinsfile)
    volumes:
      - .:/usr/share/nginx/html
    restart: always
