apiVersion: v1
kind: Service
metadata:
  name: stylehub-service
  labels:
    app: stylehub
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: stylehub
